name: CI

on:
  pull_request:
    types: [ opened, synchronize ]
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  terraform_test_workflow: 
    name: Terraform Test
    uses: ./.github/workflows/terraform_tests.yml
    secrets: inherit


  